export enum APP {
    GOTO = '@app/goto',
    INITIALIZE_REQUEST = '@app/initialize-request',
    INITIALIZE_RESPONSE = '@app/initialize-response',
    SET_READY = '@app/set-ready',
    START_LOADING = '@app/start-loading',
    STOP_LOADING = '@app/stop-loading',
    CLEAR_LOADING = '@app/clear-loading',
    START_ERROR = '@app/start-error',
    STOP_ERROR = '@app/stop-error',
    CLEAR_ERROR = '@app/clear-error',
    
    INIT_CORRELATION = '@app-initialize',
    SET_READY_CORRELATION = '@app-initialize',
    GOTO_CORRELATION = '@app-goto',
    START_LOADING_CORRELATION = '@app-start-loading',
    STOP_LOADING_CORRELATION = '@app-stop-loading',
    CLEAR_LOADING_CORRELATION = '@app-clear-loading',
    START_ERROR_CORRELATION = '@app-start-error',
    STOP_ERROR_CORRELATION = '@app-stop-error',
    CLEAR_ERROR_CORRELATION = '@app-clear-error',
}
