export enum STATUS_ACTION_STATE_M {
  IDLE = '[STATUS ACTION STATE M] IDLE',
  PENDING = '[STATUS ACTION STATE M] PENDING',
  CANCELED = '[STATUS ACTION STATE M] CANCELED',
  ERRORED = '[STATUS ACTION STATE M] ERRORED',
  RESOLVED = '[STATUS ACTION STATE M] RESOLVED',
}
